# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BX-RxSwift-1' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift',    '~> 2.0'
    pod 'RxCocoa',    '~> 2.0'
  # Pods for BX-RxSwift-1

  target 'BX-RxSwift-1Tests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 2.0'
    pod 'RxTests',    '~> 2.0'
	# Pods for testing
  end

  target 'BX-RxSwift-1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
