# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BX-RxSwift-2' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift',    '~> 2.0'
    pod 'RxCocoa',    '~> 2.0'
  # Pods for BX-RxSwift-2

  target 'BX-RxSwift-2Tests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 2.0'
    pod 'RxTests',    '~> 2.0'
    # Pods for testing
  end

  target 'BX-RxSwift-2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
